### ISSUE TITLE
qudoコマンド関連

### ISSUE THREAD

**Issue by makamaka** [nekokak/qudo#1]
お世話になっております。
posgresqlで使ってみて気付いたことが2点あります。

Qudo::TestのDATAセクション
PostgreSQL用の部分はキーをpostgresではなくPgにする必要があります。

qudoのヘルプ
--dbの引数にdbname=など、ドライバ毎に必要とする書式もつける必要があることが書かれてあると嬉しいです。

(posgresqlでの例)
  qudo --db dbname=hogehoge --rdbms Pg  --user makamaka --pass foobar

**Comment by karupanerura** [comment]
Pgでもうまく動くようになりました！
